name: "Build and deploy Github pages"

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Install Pandoc dependencies"
        run: |
          sudo apt get install -y pandoc git 
          curl -sSL https://get.haskellstack.org/ | sh
          git clone https://github.com/jez/pandoc-sidenote
          cd pandoc-sidenote
          stack build
          stack install

      - name: "Build Doc"
        run: make

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/
